server {
    listen 80;
    server_name studentloancalculator.danielskerman.com;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name studentloancalculator.danielskerman.com;

    ssl_certificate /etc/letsencrypt/live/studentloancalculator.danielskerman.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/studentloancalculator.danielskerman.com/privkey.pem;

    location / {
        proxy_pass http://127.0.0.1:3001;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:8000/;
    }
}